name: Check

on:
  pull_request:
    # Run on to branches with an open PR
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - feature/*
      - dev
    # Do not run on tags
    # tags-ignore:
    #   - "*"
    paths-ignore:
      - '**.md'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm # npm, yarn or pnpm

      - name: Env
        run: node -v && npm -v

      - name: Install
        run: npm ci --prefer-offline # npm ci or yarn

      # https://stackoverflow.com/questions/67307001/how-to-run-commitlint-in-github-workflow-on-every-commit-of-a-push
      # https://github.com/marketplace/actions/commit-linter
      - name: commitlint
        uses: wagoid/commitlint-github-action@v4
        # pull_request
        # run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      # https://github.com/marketplace/actions/lint-action
      # 需要结合 lint-staged 做 lint
      - name: Prettier
        run: npm run prettier -- --list-different

      # - name: Eslint
      #   run: npm run eslint -- --max-warnings 0

      - name: Test
        run: npm test
