name: CI Check

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - feature/*
      - dev
    paths-ignore:
      - '**.md'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm # or npm, pnpm

      - name: Env
        run: node -v && npm -v

      - name: Install dependencies
        run: npm ci # or npm ci

      - name: Prettier format
        run: npm run prettier
      - name: commitlint
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Test
        run: npm test
